<?php
$title = "Tales of Demons & Gods";
$chTitle = "<b>Chapter 18 – Inscription Master?</b>";
$lilnav = "
	<p style='float:left;'><a href='Ch17.php'><b>Previous Chapter</b></a></p>
	<p style='float:right;'><a href='Ch19.php'><b>Next Chapter</b></a></p>
	";
$chapter = " $lilnav <br><br><hr>
<p>The night slowly arrives, moon shined brightly, covering everything with a veil.

</p><p><b>Training grounds.</b>

</p><p>Nie Li walking towards the area where he first met Xiao Ning’er. Seeing far away, under the moonlight, there standing quietly was Xiao Ning’er. It seems that today she went through meticulous dressing up. Pure black hair cascading down, studded with silver ribbons. White delicate face, slender eyebrows, elegant and refined, without the slightest sense of reality.

</p><p>Really worth being a beauty on par with Ye Ziyun.

</p><p>“Thought you weren’t coming?” Xiao Ning’er’s eyes fell on Nie Li.

</p><p>“How can that be, I’m someone that keeps my promises.” Nie Li faintly smiled saying, “No matter how busy I am, first I have to treat the illness on your body.”

</p><p>“Thank you.” Xiao Ning’er whispered, lowering her head. Her heart  filled with gratitude.

</p><p>Nie Li lowered his head looking at Xiao Ning’er. Xiao Ning’er’s outfit seems to be more attractive compared to her usual. That white silk dress showing her seductive figure, from her chest the long dress stretches all the way to the knee. Slender legs shaped by diligent practice and full of elasticity could be seen.

</p><p>“Should be a little better by now.” Nie Li held onto Xiao Ning’er’s feet. Her delicate ankle, was as beautiful as sparkling crystal, smooth and delicate. The bruise that was there had slightly lighten.

</p><p>“Yeah, it has,” Xiao Ning’er nodded her head. Her heart was filled with gratitude for Nie Li. After being massaged by Nie Li, these few nights she slept especially soundly, unlike before where it was torturing.

</p><p>Although she has been massaged once before by Nie Li, when her feet were being held by Nie Li, her face couldn’t help to show a little shyness.

</p><p>While helping Xiao Ning’er, Nie Li asked “I have a favor to ask you, I wonder if you can help me?”

</p><p>“No matter what is it, as long as it can be done.” Xiao Ning’er’s eyes filled with sincerity.

</p><p>“I have 10 thousand demon spirit coins here, I want you to send someone to the herb store and help me buy Purple Haze Grass.” Nie Li said.

</p><p>“Purple Haze Grass?” Xiao Ning’er were confused by it and asked, “What do you need Purple Haze Grass for?” Purple Haze Grass is a type of extremely cheap herb, usually only used for its’ smoke. Upon drying the Purple Haze Grass then burn it as firewood, the smoke generated by it had an insect repellant effect.

</p><p>There’s a lot of Purple Haze Grass and it is very cheap. 1 demon spirit coin can buy a lot of it. Every year, every household in Glory City burns an unimaginable amount of it.

</p><p>Other than using the smoke, Purple Haze Grass has no other usage. So, what does Nie Li need such large amount of Purple Haze Grass for?

</p><p>“I naturally have a use for it.” Nie Li said, the reason why he wanted to let Xiao Ning’er help him is because that if Xiao Ning’er were to be the one handling it, it wouldn’t attract much attention. Nie Li currently too eye-grabbing, therefore he has to be low-key.

</p><p>“How much Purple Haze Grass do you need?”

</p><p>“The more the better, I want all the Purple Haze Grass that is out there on the market.” Nie Li said.

</p><p>Xiao Ning’er doesn’t get it, what can this large amount of Purple Haze Grass be used for?

</p><p>“Leave this matter to me. I will help you pay first, 10 thousand demon spirit coins isn’t a matter to me!” Although Xiao Ning’er’s family is slightly declining, it’s still one of the aristocratic families. Xiao Ning’er, as one of it’s members as well as having extraordinary talent, hasn’t lacked money. She usually doesn’t spend any money, so having  saved all her money,  she has accumulated hundred thousands demon spirit coins.

</p><p>Nie Li thought for a moment and nodded his head saying “Okay, you’ll help me buy it first, the more the better. Whatever you pay on my part, I’ll return you double.”

</p><p>“No need, this amount of money isn’t much.” Xiao Ning’er quickly added. She was delighted that she is able to help Nie Li, after all Nie Li’s kindness to her was too great. She still didn’t know how to repay him, a bit of demon spirit coins couldn’t balance her gratitude.

</p><p>After the massaging of her leg finished, Xiao Ning’er’s face redden. Even though it was done before, massaging that awkward spot she was still very shy. She lowered her head and silently unbuttoned the buttons one by one. Today, Xiao Ning’er had a pink lace ribbon around her chest, causing her to be more charming and attractive than before. That slightly bulged area and that delicate white skin was faintly discernible.

</p><p>The pink allure, more sexy than before, revealed a faint ravine. Nie Li quickly shifted his gaze away, focusing on helping Xiao Ning’er to massage her bruise.

</p><p>“Did you take the medicine when you went back?” Nie Li asked, both his hand gently kneading on the bruise, as well as the surrounding area. The bruise slowly spreads and begins to disperse, while from time to time he felt a seductive softness.

</p><p>“En,” Xiao Ning’er’s face flushed red, charming and attractive. Thinking about Nie Li helping her to modify her cultivation technique earlier on, she put on a serious look asking, “Nie Li, ever since my cultivation technique has been modified by you, my soul force gotten a lot stronger. I feel that you are a real genius, although everyone has yet to take notice of your talents yet, but when the day you reveal your talent to the public, you will definitely shine!”

</p><p>Xiao Ning’er stared at Nie Li’s handsome face becoming slightly intoxicated by it. Deep within her heart flashed a sense of loneliness and sadness, because when the day Nie Li shines arrives, she would no longer be able to stand by his side. Under such pressure, Xiao Ning’er has been practising very hard for the past few days.

</p><p>Hearing Xiao Ning’er’s words, Nie Li slightly smiled. He knows that Xiao Ning’er is encouraging him. After his rebirth, Nie Li’s heart is already very strong. He had no doubts that he will one day stand at the peak. Aiming to be a powerful existence far beyond Xiao Ning’er’s and others’ imaginations!

</p><p>But nevertheless, Nie Li is grateful for Xiao Ning’er’s concern.

</p><p><b>Sacred family.</b>

</p><p><b>Hall of Main Affairs Elder.</b>

</p><p>The Main Affair Elder of Sacred family, Shen Ming, is a silver rank demon spiritist. Although his cultivation isn’t very strong, he still has the position within the Sacred family because he is capable in handling Sacred family’s affairs.

</p><p>After hearing the report, Shen Ming wrath appeared on his face.

</p><p>“A student of the fighter apprentice class dared to challenge my Sacred family!” Shen Ming exposing a brutal look on his face, Nie Li’s exposure of <<Scarlet Sunburst>> inscription pattern caused bad impression of them by various families. In order to remove their bad impression, Shen Ming used a lot of means to send people to various families to explain.

</p><p>This matter affected Sacred family’s fundamental interest, but the Sacred family couldn’t go after Nie Li because they heard that certain powerful figure took an interest in him.

</p><p>Just a few days later, another piece of news came, Nie Li beat up Shen Yue, a direct descendent of Sacred family.

</p><p>“Isn’t Young Master Shen Yue soon going to reach the 1-star bronze rank? How could he not be Nie Li’s opponent?” Puzzled, Shen Ming looked at the underling below him.

</p><p>That underling felt the chill within Shen Ming’s expression, which sent shivers down his spine, before saying, “I’m not very sure of it, Young Master Shen Yue said that his strength and soul force is clearly above Nie Li, but was not sure what demonic magic Nie Li used and to defeat Young Master Shen Yue.”

</p><p>Hearing the words of his underling, Shen Ming frowned. ‘What demonic magic? He’s definitely not as good as the other and found some excuse after he lost, but how strong could a student from fighter apprentice class be? Probably not even 1-star bronze rank.’

</p><p>“Main Affair Elder, should we report this matter to the House Master?”

</p><p>“No, this matter cannot be told to the House Master. House Master is trying to breakthrough into becoming a legend rank demon spiritist. As long as it’s not a matter of life and death of the family, then there wouldn’t be a need for House Master to know.” In Shen Ming’s view, Nie Li couldn’t pose any threat to Sacred family, “Did you find out what family does Nie Li belongs to?”

</p><p>“Yes, Elder, we have already checked, it’s Heavenly Mark Family!”

</p><p>“Heavenly Mark Family? Heh heh, how could a normal noble family challenge us, a major family? This ignorant brat probably stumbled across the origin of <<Scarlet Sunburst>> inscription pattern and couldn’t wait to show off with it.” Shen Ming thought, it’s impossible for the Sacred Family to put a small noble family in their sights. If he were to send someone to take care of the Heavenly Mark Family, other families will definitely find out and at that time the Sacred Family would definitely be looked as petty, “Let Young Master Shen Fei take note of this Nie Li, if a few teenagers were to have some conflicts and fought in school then it’d be reasonable to understand!”

</p><p>Upon hearing it, Shen Ming’s underling immediately understood the meaning behind it. Shen Fei is already a 1-star silver demon spiritist, his strength is more to enough to handle Nie Li. Shen Ming’s meaning is to let Young Master Shen Fei to beat Nie Li up in school.

</p><p>Thinking again, Shen Ming said “The storm caused by this matter is not gone yet, wait for awhile then tell him. Let the storm subsidise a little, then let Young Master Shen Fei act!” As the Main Affair Elder of Sacred Family, he must handle it perfectly, can’t let anyone to gossip.

</p><p>“Yes!”

</p><p><b>City Lord’s Mansion, in Ye Ziyun’s room, the room was very well decorated and exquisite.</b>

</p><p>In front of a desk, Ye Ziyun’s head was bowed down to research something. She occasionally stopped, furrowed her brows in thought. She had been trying to find the <<Icy Wind, Sudden Snow>> pattern drawn by Nie Li in ancient books but failed to find any.

</p><p>Where did Nie Li find this Inscription Pattern?

</p><p>In a moment, a beautiful woman wearing blue veil came in.

</p><p>“Miss, what matters did you call me for?” the beautiful married woman revealed a humble smile.

</p><p>“Aunt Xue, you are an inscription master, do you know the origin of this inscription pattern?” Ye Ziyun raised her head looking at the beautiful married woman and asked.

</p><p>Xue Yin’s gaze fell onto the paper in front of Ye Ziyun. Her eyes filled with astonishment as she asked, “Miss, where did you get this inscription pattern, how come I’ve never seen it before?”

</p><p>“Even Aunt Xue has never seen this inscription pattern before?” Ye Ziyun was shocked, Xue Yin is a Inscription Master! Even she have never seen it before, could this be randomly drawn by Nie Li?

</p><p>“Looks like <<Icy Wind, Sudden Snow>>, but at the same time it’s not. It seems like it’s much stronger than <<Icy Wind, Sudden Snow>>.” Xue Yin made a few hand gesture on the inscription pattern, saying, “These well-proportioned lines, not sure which master is this work from, Xue Yin admits defeat. Could it be that Miss met an inscription master?”

</p><p>‘Nie Li is an inscription master? How could that be possible? Nie Li can’t be an inscription master at his age!’ Thinking of how Nie Li took the pen with ease and with a few stoke, drew this inscription pattern, Ye Ziyun’s heart became even more confused!</p>
<hr>
$lilnav
";

require('Template.php');
?>